export const LAYER_CATEGORIES = [
  { id: "base", name: "Capas base" },
  { id: "vector", name: "Capas vectoriales" },
  { id: "raster", name: "Capas ráster" },
  { id: "analysis", name: "Capas de análisis" },
];

export const INITIAL_VIEW = {
  center: [14.6349, -90.5069],
  zoom: 8,
  cesiumDestination: {
    longitude: -90.5069,
    latitude: 14.6349,
    height: 850000,
  },
};

export const MAP_LAYERS = [
  // Edita esta lista para agregar, ocultar o reorganizar capas sin tocar componentes.
  {
    id: "esri-world-imagery",
    name: "Esri World Imagery",
    technicalName: "",
    workspace: "",
    type: "base",
    category: "base",
    service: "tile",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attribution: "Tiles &copy; Esri",
    visible: true,
    opacity: 1,
    queryable: false,
    legendUrl: null,
  },
  {
    id: "departamentos",
    name: "Departamentos",
    technicalName: "departamentos",
    workspace: "energia_eolica",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: true,
    opacity: 0.85,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "municipios",
    name: "Municipios",
    technicalName: "municipios",
    workspace: "energia_eolica",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.75,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "urbanizacion",
    name: "Urbanización",
    technicalName: "urbanizacion",
    workspace: "el_salvador",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.75,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "red_vial",
    name: "Red vial",
    technicalName: "red_vial",
    workspace: "energia_eolica",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.9,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "red_electrica",
    name: "Red eléctrica",
    technicalName: "red_electrica",
    workspace: "energia_eolica",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.9,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "areas_protegidas",
    name: "Áreas protegidas",
    technicalName: "areas_protegidas",
    workspace: "energia_eolica",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.6,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "velocidad_viento",
    name: "Velocidad del viento",
    technicalName: "velocidad_viento",
    workspace: "energia_eolica",
    type: "raster",
    category: "raster",
    service: "wms",
    visible: true,
    opacity: 0.65,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "densidad_potencia",
    name: "Densidad de potencia",
    technicalName: "densidad_potencia",
    workspace: "energia_eolica",
    type: "raster",
    category: "raster",
    service: "wms",
    visible: false,
    opacity: 0.65,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "pendiente",
    name: "Pendiente",
    technicalName: "pendiente",
    workspace: "energia_eolica",
    type: "raster",
    category: "raster",
    service: "wms",
    visible: false,
    opacity: 0.65,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "distancia_red_electrica",
    name: "Distancia a red eléctrica",
    technicalName: "distancia_red_electrica",
    workspace: "energia_eolica",
    type: "analysis",
    category: "analysis",
    service: "wms",
    visible: false,
    opacity: 0.65,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "idoneidad_eolica",
    name: "Idoneidad eólica",
    technicalName: "idoneidad_eolica",
    workspace: "energia_eolica",
    type: "analysis",
    category: "analysis",
    service: "wms",
    visible: true,
    opacity: 0.72,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "zonas_optimas",
    name: "Zonas óptimas",
    technicalName: "zonas_optimas",
    workspace: "energia_eolica",
    type: "analysis",
    category: "analysis",
    service: "wms",
    visible: false,
    opacity: 0.82,
    queryable: true,
    legendUrl: null,
  },
];

export default MAP_LAYERS;
