export const LAYER_CATEGORIES = [
  { id: "base", name: "Capas base" },
  { id: "vector", name: "Capas vectoriales" },
  { id: "raster", name: "Capas ráster" },
  { id: "analysis", name: "Capas de análisis" },
];

export const INITIAL_VIEW = {
  center: [14.6349, -90.5069],
  zoom: 8,
};

export const MAP_LAYERS = [
  // Edita esta lista para agregar, ocultar o reorganizar capas sin tocar componentes.
  {
    id: "osm",
    name: "OpenStreetMap",
    technicalName: "",
    workspace: "",
    type: "base",
    category: "base",
    service: "tile",
    url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    attribution: "&copy; OpenStreetMap contributors",
    visible: true,
    opacity: 1,
    queryable: false,
    legendUrl: null,
  },
  {
    id: "cartodb_light",
    name: "CartoDB Claro",
    technicalName: "",
    workspace: "",
    type: "base",
    category: "base",
    service: "tile",
    url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
    attribution: "&copy; OpenStreetMap contributors &copy; CARTO",
    visible: false,
    opacity: 1,
    queryable: false,
    legendUrl: null,
    subdomains: "abcd",
    maxZoom: 20,
  },
  {
    id: "departamentos",
    name: "Departamentos",
    technicalName: "departamentos",
    workspace: "el_salvador",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.85,
    queryable: true,
    legendUrl: null,
    forceLegendLabels: true,
  },
  {
    id: "municipios",
    name: "Municipios",
    technicalName: "municipios",
    workspace: "el_salvador",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.75,
    queryable: true,
    legendUrl: null,
    forceLegendLabels: true,
  },
  {
    id: "plantas_gen_electricas",
    name: "Plantas de generación eléctrica",
    technicalName: "plantas_gen_electricas",
    workspace: "el_salvador",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.75,
    queryable: true,
    legendUrl: null,
    forceLegendLabels: true,

  },
  {
    id: "red_vial",
    name: "Red vial",
    technicalName: "red_vial",
    workspace: "el_salvador",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.9,
    queryable: true,
    legendUrl: null,
    forceLegendLabels: true,
  },
  {
    id: "red_electrica",
    name: "Red eléctrica",
    technicalName: "red_electrica",
    workspace: "el_salvador",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.9,
    queryable: true,
    legendUrl: null,
    forceLegendLabels: true,
  },
  {
    id: "restricciones_ambientales",
    name: "Restricciones ambientales",
    technicalName: "restricciones_ambientales",
    workspace: "el_salvador",
    type: "vector",
    category: "vector",
    service: "wms",
    visible: false,
    opacity: 0.6,
    queryable: true,
    legendUrl: null,
    forceLegendLabels: true,
  },
  {
    id: "velocidad_viento",
    name: "Velocidad del viento",
    technicalName: "velocidad_viento",
    workspace: "el_salvador",
    type: "raster",
    category: "raster",
    service: "wms",
    visible: false,
    opacity: 0.65,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "densidad_potencia",
    name: "Densidad de potencia",
    technicalName: "densidad_potencia",
    workspace: "el_salvador",
    type: "raster",
    category: "raster",
    service: "wms",
    visible: false,
    opacity: 0.65,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "pendiente",
    name: "Pendiente",
    technicalName: "pendiente",
    workspace: "el_salvador",
    type: "raster",
    category: "raster",
    service: "wms",
    visible: false,
    opacity: 0.65,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "distribucion_poblacion2",
    name: "Distribucion de población",
    technicalName: "distribucion_poblacion2",
    workspace: "el_salvador",
    type: "raster",
    category: "raster",
    service: "wms",
    visible: false,
    opacity: 0.65,
    queryable: false,
    legendUrl: null,
  },
  {
    id: "idoneidad_eolica_final",
    name: "Zonas preliminares",
    technicalName: "idoneidad_eolica_final",
    workspace: "el_salvador",
    type: "analysis",
    category: "analysis",
    service: "wms",
    visible: false,
    opacity: 0.72,
    queryable: true,
    legendUrl: null,
  },
  {
    id: "zonas_candidatas_areass",
    name: "Zonas candidatas",
    technicalName: "zonas_candidatas_areas",
    workspace: "el_salvador",
    type: "analysis",
    category: "analysis",
    service: "wms",
    visible: false,
    opacity: 0.82,
    queryable: true,
    legendUrl: null,
    forceLegendLabels: true,
  },
];

export default MAP_LAYERS;
